### PR TITLE
Fix neuron mesh generation rebase

### PR DESCRIPTION
**Pull request by hanslovsky**

### CODE REVIEW

**Comment by hanslovsky** [comment]
Slight mishap with the github ui ended up having master as base branch instead of javafx-generic-listeners. Even after changing base branch to the correct branch, github would still show the wrong commits. When creating PRs, github becomes very slow now, because master is selected as default base, and the diff is a lot of commits. The sooner we merge back into master, the sooner we will not face this issue anymore.

**Comment by axtimwalde** [comment]
Merging with master is ok any time.  I released a hopefully last 0.0.3-beta-1 of 'old' BigCAT for dependencies earlier last week.

**Comment by axtimwalde** [comment]
BTW, rebasing large bunches of commits is generally a bad idea, particularly if it is for pure aesthetics.

**Comment by hanslovsky** [comment]
In general, I agree with that. I tried to squash the commits into fewer, more meaningful commits. Unfortunately, that branch was very explorative and didn't allow for that. That's why I chose to squash into a single commit with a clear commit message that gives a comprehensive high-level summary.

**Pull request closed without merging**
